#!/bin/bash
#SBATCH -C gpu
#SBATCH -G 1
#SBATCH --job-name=gpu_cpu_ws_weak_large
#SBATCH --output=gpu_cpu_ws_weak_large.out
#SBATCH --error=gpu_cpu_ws_weak_large.err
#SBATCH -t 30
#SBATCH -c 10

srun ./program_gpu dna ../test-data/dna-reference.fasta ../test-data/dna-query.fasta ./out_file 1500 7 1
srun ./program_gpu dna ../test-data/dna-reference.fasta ../test-data/dna-query.fasta ./out_file 2000 7 1
srun ./program_gpu dna ../test-data/dna-reference.fasta ../test-data/dna-query.fasta ./out_file 2500 7 1
