#!/bin/bash
#SBATCH -C gpu
#SBATCH -G 2
#SBATCH --job-name=muaaz_set2
#SBATCH --output=muaaz_set2.out
#SBATCH --error=muaaz_set2.err
#SBATCH -t 30
#SBATCH -c 20


srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 1 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 2 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 3 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 4 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 5 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 6 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 7 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 8 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 9 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 10 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 11 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 12 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 13 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 14 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 15 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 16 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 17 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 18 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 19 1
srun ./program_gpu dna /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/ref_set_2.fasta /global/cscratch1/sd/mgawan/sw-benchmarks/dna-testing/read_set_2.fasta ./out_file 1 20 1

